### ISSUE TITLE
Mudar icones sociais para icon fonte

### ISSUE THREAD

**Issue by moyses** [devinsanta/website#3]
Acho que seria interessante colocar alem de ser bom, seria um aprendizado a mais também.
Facil de implementar ja usei o socicon qualquer duvida estamos ai.
@tobiaszwink @ricardogouveia3 

http://fontello.com/
http://www.socicon.com/

**Comment by ricardogouveia3** [comment]
Já falei isso com o @tobiaszwink. O pessoal do floripaJS usa o fontello. Vamos precisar mudar pra poder mudar a cor do ícone com o :hover.
